apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-app
  namespace: nextgis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-app
  template:
    metadata:
      labels:
        app: postgres-app
    spec:
      containers:
      - name: postgres-app-container
        image: registry.gitlab.com/nextgis/ngwdocker/ext-wl/postgres:2.4.1
        ports:             
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: PasswordDif123) 
