apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngw
  namespace: nextgis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngw-app
  template:
    metadata:
      labels:
        app: ngw-app
    spec:
      containers:
      - name: ngw-app-container
        image: registry.gitlab.com/nextgis/ngwdocker/ext-wl/app:2.4.1
        ports:             
        - containerPort: 8080
      env:
      - name: NEXTGISWEB__CORE__DATABASE__PASSWORD
        value: PasswordDif123)
