apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngw-app
  namespace: nextgis
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ngw-app
  template:
    metadata:
      labels:
        app: ngw-app
    spec:
      containers:
      - name: ngw-app-container
        image: registry.gitlab.com/nextgis/ngwdocker/ext-wl/app:2.4.1
        ports:             
        - containerPort: 8080
        volumeMounts:
          - mountPath: "/opt/ngw/secret"
            name: postgres-secret
            readOnly: true
      volumes:
        - name: postgres-secret
          secret:
            secretName: postgres-secret
