apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-app
  namespace: nextgis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-app
  template:
    metadata:
      labels:
        app: postgres-app
    spec:
      containers:
      - name: postgres-app-container
        image: harbor.nextgis.net/gazprom/ngw/postgres:0.16.2
        ports:             
        - containerPort: 5432
        volumeMounts:
          - mountPath: "/opt/ngw/secret"
            name: postgres-secret
            readOnly: true
          - mountPath: /opt/ngw/data/postgres
            name: pvc-postgres
      initContainers:
      - args:
        - chown -R 1000:1000 /opt/ngw/data/postgres
        command:
        - sh
        - -c
        name: initcont
        image: busybox:latest
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /opt/ngw/data/postgres
          name: pvc-postgres
      volumes:
        - name: postgres-secret
          secret:
            secretName: postgres-secret
        - name: pvc-postgres
          persistentVolumeClaim:
            claimName: pvc-postgres
