apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngw-app
  namespace: nextgis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngw-app
  template:
    metadata:
      labels:
        app: ngw-app
    spec:
      containers:
      - name: ngw-app-container
        image: harbor.nextgis.net/gazprom/ngw/app:0.16.2
        ports:             
        - containerPort: 8080
        volumeMounts:
          - mountPath: "/opt/ngw/secret"
            name: postgres-secret
            readOnly: true
      imagePullSecrets:
      - name: harbor
      volumes:
        - name: postgres-secret
          secret:
            secretName: postgres-secret
