apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngw-app
  namespace: nextgis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngw-app
  template:
    metadata:
      labels:
        app: ngw-app
    spec:
      containers:
      - name: ngw-app-container
        image: harbor.nextgis.net/gazprom/ngw/app:0.16.2
        ports:             
        - containerPort: 8080
        volumeMounts:
          - mountPath: "/opt/ngw/secret"
            name: postgres-secret
            readOnly: true
          - mountPath: /opt/ngw/data/app
            name: pvc-ngw
      initContainers:
      - args:
        - chown -R 1000:1000 /opt/ngw/data/app
        command:
        - sh
        - -c
        name: initcontngw
        image: busybox:latest
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /opt/ngw/data/app
          name: pvc-ngw
      volumes:
        - name: postgres-secret
          secret:
            secretName: postgres-secret
        - name: pvc-ngw
          persistentVolumeClaim:
            claimName: pvc-ngw
