apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ngw
  namespace: nextgis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ngw-gera-storage
  